# Generated by Django 5.1.3 on 2025-08-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="razorpay_invoice_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="invoice",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_gateway",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("razorpay", "RazorpayX")],
                default="stripe",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_gateway",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("razorpay", "RazorpayX")],
                default="stripe",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="razorpay_customer_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subscription",
            name="razorpay_subscription_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="razorpay_monthly_plan_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="razorpay_product_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="razorpay_yearly_plan_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Credit Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                    ("razorpay", "RazorpayX"),
                    ("upi", "UPI"),
                    ("netbanking", "Net Banking"),
                    ("wallet", "Wallet"),
                ],
                default="stripe",
                max_length=20,
            ),
        ),
    ]
