version: '3.8'

services:
  gst-api:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - DEBUG=true
      - LOG_LEVEL=INFO
      - SESSION_TIMEOUT=300
      - REQUEST_TIMEOUT=30
      - RATE_LIMIT_CAPTCHA=20
      - RATE_LIMIT_GST_DETAILS=10
      - CORS_ORIGINS=*
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for session storage (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   command: redis-server --appendonly yes

  # Optional: Nginx reverse proxy (uncomment if needed)
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - gst-api
  #   restart: unless-stopped

volumes:
  logs:
  # redis_data:  # Uncomment if using Redis

networks:
  default:
    name: gst-api-network