# Generated by Django 4.2.7 on 2025-08-12 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GSTRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("method", models.CharField(default="POST", max_length=10)),
                ("endpoint", models.CharField(max_length=200)),
                ("request_headers", models.JSONField(blank=True, default=dict)),
                ("request_body", models.JSONField(blank=True, default=dict)),
                ("request_params", models.JSONField(blank=True, default=dict)),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                (
                    "credits_consumed",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
                ),
                (
                    "billing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("charged", "Charged"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("rate_limited", "Rate Limited"),
                            ("insufficient_credits", "Insufficient Credits"),
                            ("invalid_request", "Invalid Request"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gst_requests",
                        to="api_management.apikey",
                    ),
                ),
            ],
            options={
                "verbose_name": "GST Request",
                "verbose_name_plural": "GST Requests",
                "db_table": "gst_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GSTService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "endpoint_path",
                    models.CharField(help_text="API endpoint path", max_length=100),
                ),
                (
                    "credit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Credits consumed per request",
                        max_digits=8,
                    ),
                ),
                ("rate_limit_per_minute", models.IntegerField(default=10)),
                ("rate_limit_per_hour", models.IntegerField(default=100)),
                ("rate_limit_per_day", models.IntegerField(default=1000)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, help_text="Requires premium subscription"
                    ),
                ),
                ("documentation_url", models.URLField(blank=True)),
                ("example_request", models.JSONField(blank=True, default=dict)),
                ("example_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GST Service",
                "verbose_name_plural": "GST Services",
                "db_table": "gst_services",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GSTWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "secret_key",
                    models.CharField(
                        help_text="Secret key for webhook verification", max_length=100
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list, help_text="List of events to trigger webhook"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("max_retries", models.IntegerField(default=3)),
                ("retry_delay_seconds", models.IntegerField(default=60)),
                ("total_deliveries", models.IntegerField(default=0)),
                ("successful_deliveries", models.IntegerField(default=0)),
                ("failed_deliveries", models.IntegerField(default=0)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gst_webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GST Webhook",
                "verbose_name_plural": "GST Webhooks",
                "db_table": "gst_webhooks",
            },
        ),
        migrations.CreateModel(
            name="GSTWebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("http_status_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("attempt_number", models.IntegerField(default=1)),
                ("max_attempts", models.IntegerField(default=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("scheduled_at", models.DateTimeField()),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_deliveries",
                        to="gst_services.gstrequest",
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="gst_services.gstwebhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "GST Webhook Delivery",
                "verbose_name_plural": "GST Webhook Deliveries",
                "db_table": "gst_webhook_deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="gstrequest",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="gst_services.gstservice",
            ),
        ),
        migrations.AddField(
            model_name="gstrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gst_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="GSTCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gstin", models.CharField(db_index=True, max_length=15, unique=True)),
                ("cached_data", models.JSONField()),
                ("cache_hit_count", models.IntegerField(default=0)),
                ("last_verified_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("is_valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GST Cache",
                "verbose_name_plural": "GST Cache",
                "db_table": "gst_cache",
                "indexes": [
                    models.Index(fields=["gstin"], name="gst_cache_gstin_3731bf_idx"),
                    models.Index(
                        fields=["expires_at"], name="gst_cache_expires_c52da9_idx"
                    ),
                    models.Index(
                        fields=["is_valid"], name="gst_cache_is_vali_d63cd4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GSTBulkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("total_records", models.IntegerField()),
                ("processed_records", models.IntegerField(default=0)),
                ("successful_records", models.IntegerField(default=0)),
                ("failed_records", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_file_name", models.CharField(blank=True, max_length=255)),
                ("output_file_url", models.URLField(blank=True)),
                (
                    "total_credits_consumed",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "estimated_completion_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_gst_requests",
                        to="api_management.apikey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_gst_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GST Bulk Request",
                "verbose_name_plural": "GST Bulk Requests",
                "db_table": "gst_bulk_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GSTVerificationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gstin", models.CharField(db_index=True, max_length=15)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("trade_name", models.CharField(blank=True, max_length=255)),
                ("business_type", models.CharField(blank=True, max_length=100)),
                ("constitution", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                ("state_code", models.CharField(blank=True, max_length=2)),
                ("state_name", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("registration_date", models.DateField(blank=True, null=True)),
                ("cancellation_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                            ("invalid", "Invalid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Confidence score (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_result",
                        to="gst_services.gstrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "GST Verification Result",
                "verbose_name_plural": "GST Verification Results",
                "db_table": "gst_verification_results",
                "indexes": [
                    models.Index(fields=["gstin"], name="gst_verific_gstin_95cd4b_idx"),
                    models.Index(
                        fields=["status"], name="gst_verific_status_aea06c_idx"
                    ),
                    models.Index(
                        fields=["is_verified"], name="gst_verific_is_veri_c3a40c_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="gstrequest",
            index=models.Index(
                fields=["user", "-created_at"], name="gst_request_user_id_2f8c9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gstrequest",
            index=models.Index(
                fields=["api_key", "-created_at"], name="gst_request_api_key_8865e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gstrequest",
            index=models.Index(
                fields=["service", "-created_at"], name="gst_request_service_da0a19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gstrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="gst_request_status_eb2c1b_idx"
            ),
        ),
    ]
