# Generated by Django 4.2.7 on 2025-08-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the API key", max_length=100
                    ),
                ),
                (
                    "key_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("key_secret", models.CharField(editable=False, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allowed_ips",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of allowed IP addresses. Leave empty for no restrictions.",
                    ),
                ),
                ("rate_limit_per_minute", models.IntegerField(default=60)),
                ("rate_limit_per_hour", models.IntegerField(default=1000)),
                ("rate_limit_per_day", models.IntegerField(default=10000)),
                ("total_requests", models.BigIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "api_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=100)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.IntegerField()),
                (
                    "response_time_ms",
                    models.IntegerField(help_text="Response time in milliseconds"),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                (
                    "credits_used",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
                ),
                ("request_size_bytes", models.IntegerField(default=0)),
                ("response_size_bytes", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "API Usage",
                "verbose_name_plural": "API Usage Records",
                "db_table": "api_usage",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("credits", models.IntegerField(help_text="Number of API credits")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in USD", max_digits=10
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("one_time", "One Time"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        default="one_time",
                        max_length=20,
                    ),
                ),
                ("stripe_product_id", models.CharField(blank=True, max_length=100)),
                ("stripe_price_id", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_popular", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Credit Package",
                "verbose_name_plural": "Credit Packages",
                "db_table": "credit_packages",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="RateLimitTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "window_type",
                    models.CharField(
                        choices=[
                            ("minute", "Per Minute"),
                            ("hour", "Per Hour"),
                            ("day", "Per Day"),
                        ],
                        max_length=10,
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("request_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rate Limit Tracker",
                "verbose_name_plural": "Rate Limit Trackers",
                "db_table": "rate_limit_tracker",
            },
        ),
        migrations.CreateModel(
            name="UserCredits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_credits",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
                ),
                (
                    "total_purchased",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
                ),
                (
                    "total_used",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
                ),
                (
                    "trial_credits_granted",
                    models.DecimalField(decimal_places=4, default=100.0, max_digits=10),
                ),
                (
                    "trial_credits_used",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Credits",
                "verbose_name_plural": "User Credits",
                "db_table": "user_credits",
            },
        ),
    ]
