# Generated by Django 4.2.7 on 2025-08-12 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usercredits",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ratelimittracker",
            name="api_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_limits",
                to="api_management.apikey",
            ),
        ),
        migrations.AddField(
            model_name="apiusage",
            name="api_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_records",
                to="api_management.apikey",
            ),
        ),
        migrations.AddField(
            model_name="apiusage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_usage",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimittracker",
            index=models.Index(
                fields=["api_key", "window_type", "window_start"],
                name="rate_limit__api_key_c91493_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ratelimittracker",
            unique_together={("api_key", "window_type", "window_start")},
        ),
        migrations.AddIndex(
            model_name="apiusage",
            index=models.Index(
                fields=["user", "created_at"], name="api_usage_user_id_b7cc9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusage",
            index=models.Index(
                fields=["api_key", "created_at"], name="api_usage_api_key_d7d96f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusage",
            index=models.Index(
                fields=["endpoint", "created_at"], name="api_usage_endpoin_6aa3d0_idx"
            ),
        ),
    ]
