# Generated by Django 4.2.7 on 2025-08-12 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_management", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referral_code", models.CharField(max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "referrer_bonus_credits",
                    models.DecimalField(decimal_places=4, default=50.0, max_digits=10),
                ),
                (
                    "referred_bonus_credits",
                    models.DecimalField(decimal_places=4, default=25.0, max_digits=10),
                ),
                ("bonus_awarded", models.BooleanField(default=False)),
                ("bonus_awarded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "referred_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Program",
                "verbose_name_plural": "Referral Programs",
                "db_table": "referral_programs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 country code", max_length=2
                    ),
                ),
                ("country_name", models.CharField(max_length=100)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("razorpay", "Razorpay"),
                            ("paypal", "PayPal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provider_config",
                    models.JSONField(
                        default=dict,
                        help_text="Provider-specific configuration (API keys, webhook URLs, etc.)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(help_text="ISO 4217 currency code", max_length=3),
                ),
                ("currency_symbol", models.CharField(default="$", max_length=5)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "db_table": "payment_methods",
                "ordering": ["country_name"],
                "unique_together": {("country_code", "provider")},
            },
        ),
        migrations.CreateModel(
            name="APIUsageAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("total_requests", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                ("failed_requests", models.IntegerField(default=0)),
                (
                    "total_credits_used",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
                ),
                ("avg_response_time_ms", models.FloatField(default=0.0)),
                ("total_data_transferred_mb", models.FloatField(default=0.0)),
                (
                    "endpoint_usage",
                    models.JSONField(
                        default=dict, help_text="Breakdown of usage by endpoint"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Usage Analytics",
                "verbose_name_plural": "API Usage Analytics",
                "db_table": "api_usage_analytics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="api_usage_a_user_id_d343dc_idx"
                    ),
                    models.Index(
                        fields=["date", "period_type"],
                        name="api_usage_a_date_0a9e0d_idx",
                    ),
                ],
                "unique_together": {("user", "date", "period_type")},
            },
        ),
    ]
